# Automatically generated by: ros2nix --flake
{ lib, buildRosPackage, ament-copyright, ament-flake8, ament-pep257, python3Packages, rclpy, stewart-helpers, stewart-interfaces }:
buildRosPackage rec {
  pname = "ros-rolling-ik-solver";
  version = "0.0.0";

  src = ./.;

  buildType = "ament_python";
  checkInputs = [ ament-copyright ament-flake8 ament-pep257 python3Packages.pytest ];
  propagatedBuildInputs = [ python3Packages.numpy rclpy stewart-helpers stewart-interfaces ];

  meta = {
    description = "TODO: Package description";
    license = with lib.licenses; [ asl20 ];
  };
}
