# Automatically generated by: ros2nix --flake
{ lib, buildRosPackage, ament-copyright, ament-flake8, ament-pep257, python3-tf-transformations, python3Packages, rclpy, stewart-interfaces }:
buildRosPackage rec {
  pname = "ros-rolling-vision-system";
  version = "0.0.0";

  src = ./.;

  buildType = "ament_python";
  checkInputs = [ ament-copyright ament-flake8 ament-pep257 python3Packages.pytest ];
  propagatedBuildInputs = [ python3-tf-transformations python3Packages.numpy rclpy stewart-interfaces ];

  meta = {
    description = "TODO: Package description";
    license = with lib.licenses; [ "TODO-License-declaration" ];
  };
}
